//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject_Part2_DanielScholtz.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherCours
    {
        public int TeacherCourseID { get; set; }
        public Nullable<int> TeacherID { get; set; }
        public Nullable<int> CourseNumber { get; set; }
    }
}
